kind: ClusterRole
metadata:
  name: acme-controller
rules:
- apiGroups: null
  resources:
  - endpoints
  - endpoints/restricted
  - events
  - routes
  - routes/custom-host
  - routes/status
  - secrets
  - services
  verbs:
  - '*'
- apiGroups: null
  resources:
  - namespaces
  - projects
  verbs:
  - get
  - list
  - watch
